name: wid_yu
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'



dependencies:
#  old:
#    path: old
#  young:
#    path: young

  flutter:

    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.6.0
  percent_indicator: ^4.2.3
  #kakao_flutter_sdk: ^1.5.0
  flutter_naver_login: ^1.8.0
  page_transition: ^2.0.5
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  fluttertoast: ^8.0.9
  easy_stepper: ^0.6.0
  geolocator: ^10.0.0
  permission_handler: ^10.0.0
  video_player: ^2.8.1
  flutter_switch: ^0.3.2
  amazon_cognito_identity_dart_2: ^3.5.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  image: ^3.0.1
  camera: ^0.10.5+5
  flutter_blurhash: ^0.7.0
  video_trimmer: ^3.0.1
  fl_chart: ^0.45.0
  chart_sparkline: ^1.0.14
  video_editor: ^3.0.0
  chewie: ^1.7.4
  fraction: ^5.0.2
  flutter_blue: ^0.8.0
  flutter_svg: ^2.0.5
  remedi_kopo: ^0.0.2
  dots_indicator: ^3.0.0
  blur: ^3.1.0

  webview_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
#    #    - .env
    - assets/common/
    - assets/common/account/
    - assets/common/mission/
    - assets/common/album/
    - assets/common/common/
    - assets/common/goal/
    - assets/common/icon/
    - assets/common/icon/mission/
    - assets/common/health-information/
    - assets/common/popup/
    - assets/common/icon/frame/
    - assets/common/user/
    - assets/young/health-information/
    - assets/young/album/
    - assets/images/old/reward/
    - assets/common/goal-conduct/
    - assets/common/alarm/
    - assets/common/health-information/graph/
    - assets/common/health-information/grey/
    - assets/images/common/account/
    - assets/images/icon/
    - assets/images/icon/heart-bit.svg
    - assets/images/user/
    - assets/images/common/mission/
    - assets/images/common/goal/
    - assets/images/mission/
    - assets/images/
    - assets/images/icon/alarm/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Body1
      fonts:
        - asset: assets/fonts/Body1.otf
    - family: Body2
      fonts:
        - asset: assets/fonts/Body2.otf
    - family: Button
      fonts:
        - asset: assets/fonts/Button.otf
    - family: Chip
      fonts:
        - asset: assets/fonts/Chip.otf
    - family: Helper
      fonts:
        - asset: assets/fonts/Helper.otf
    - family: Helper2
      fonts:
        - asset: assets/fonts/Helper2.otf
    - family: Hint
      fonts:
        - asset: assets/fonts/Hint.otf
    - family: LargeTitle
      fonts:
        - asset: assets/fonts/LargeTitle.otf
    - family: Percentage
      fonts:
        - asset: assets/fonts/Percentage.otf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Percentage.otf
    - family: SubTitle1
      fonts:
        - asset: assets/fonts/SubTitle1.otf
    - family: SubTitle2
      fonts:
        - asset: assets/fonts/SubTitle2.otf
    - family: Title1
      fonts:
        - asset: assets/fonts/Title1.otf
    - family: Title2
      fonts:
        - asset: assets/fonts/Title2.otf
    - family: Title3
      fonts:
        - asset: assets/fonts/Title3.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
